/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBriefingRouteImport } from './routes/api/briefing'
import { Route as ApiEditionRouteImport } from './routes/api/edition'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBriefingRoute = ApiBriefingRouteImport.update({
  id: '/api/briefing',
  path: '/api/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEditionRoute = ApiEditionRouteImport.update({
  id: '/api/edition',
  path: '/api/edition',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/briefing': typeof ApiBriefingRoute
  '/api/edition': typeof ApiEditionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/briefing': typeof ApiBriefingRoute
  '/api/edition': typeof ApiEditionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/briefing': typeof ApiBriefingRoute
  '/api/edition': typeof ApiEditionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/briefing' | '/api/edition'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/briefing' | '/api/edition'
  id: '__root__' | '/' | '/api/briefing' | '/api/edition'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBriefingRoute: typeof ApiBriefingRoute
  ApiEditionRoute: typeof ApiEditionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/briefing': {
      id: '/api/briefing'
      path: '/api/briefing'
      fullPath: '/api/briefing'
      preLoaderRoute: typeof ApiBriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/edition': {
      id: '/api/edition'
      path: '/api/edition'
      fullPath: '/api/edition'
      preLoaderRoute: typeof ApiEditionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBriefingRoute: ApiBriefingRoute,
  ApiEditionRoute: ApiEditionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
